#pragma once

/**
 * Name: HW2
 * Version: 1
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Enums
	// --------------------------------------------------
	/**
	 * BoneSkeletalMesh SK_PBaby.SK_PBaby
	 */
	enum class EBone_SK_PBaby : uint8_t
	{
		C_World_jnt         = 0,
		Hips_jnt            = 1,
		L_UpperLeg_jnt      = 2,
		L_Ankle_jnt         = 3,
		Spine_jnt           = 4,
		L_Shoulder_jnt      = 5,
		L_Wrist_jnt         = 6,
		Head_jnt            = 7,
		L_Ear_jnt           = 8,
		L_EarB_jnt          = 9,
		R_Ear_jnt           = 10,
		R_EarB_jnt          = 11,
		Head2_jnt           = 12,
		R_Shoulder_jnt      = 13,
		R_Wrist_jnt         = 14,
		R_UpperLeg_jnt      = 15,
		R_Ankle_jnt         = 16,
		DressRight_jnt      = 17,
		DressRightFront_jnt = 18,
		DressRightBack_jnt  = 19,
		DressBack_jnt       = 20,
		DressLeftBack_jnt   = 21,
		DressLeft_jnt       = 22,
		DressLeftFront_jnt  = 23,
		DressFront_jnt      = 24,
		Jumpscare_jnt       = 25
	};

	/**
	 * BoneSkeletalMesh SK_Minireena.SK_Minireena
	 */
	enum class EBone_SK_Minireena : uint8_t
	{
		Root          = 0,
		pelvis        = 1,
		thigh_l       = 2,
		calf_l        = 3,
		foot_l        = 4,
		ball_l        = 5,
		toe_l         = 6,
		pelvis_jiggle = 7,
		spine_01      = 8,
		neck_01       = 9,
		Head          = 10,
		head_jiggle   = 11,
		upperarm_l    = 12,
		lowerarm_l    = 13,
		hand_l        = 14,
		fingers_l     = 15,
		body_jiggle   = 16,
		skirtback     = 17,
		skirtfront    = 18,
		skirt_l       = 19,
		skirt_r       = 20,
		upperarm_r    = 21,
		lowerarm_r    = 22,
		hand_r        = 23,
		fingers_r     = 24,
		thigh_r       = 25,
		calf_r        = 26,
		foot_r        = 27,
		ball_r        = 28,
		toe_r         = 29,
		eye_l         = 30,
		eye_r         = 31
	};

	/**
	 * BoneSkeletalMesh RIG_Plushy_CircusBaby.RIG_Plushy_CircusBaby
	 */
	enum class EBone_RIG_Plushy_CircusBaby : uint8_t
	{
		C_World_jnt         = 0,
		Hips_jnt            = 1,
		L_UpperLeg_jnt      = 2,
		L_Ankle_jnt         = 3,
		Spine_jnt           = 4,
		L_Shoulder_jnt      = 5,
		L_Wrist_jnt         = 6,
		Head_jnt            = 7,
		L_Ear_jnt           = 8,
		L_EarB_jnt          = 9,
		R_Ear_jnt           = 10,
		R_EarB_jnt          = 11,
		Head2_jnt           = 12,
		R_Shoulder_jnt      = 13,
		R_Wrist_jnt         = 14,
		R_UpperLeg_jnt      = 15,
		R_Ankle_jnt         = 16,
		DressRight_jnt      = 17,
		DressRightFront_jnt = 18,
		DressRightBack_jnt  = 19,
		DressBack_jnt       = 20,
		DressLeftBack_jnt   = 21,
		DressLeft_jnt       = 22,
		DressLeftFront_jnt  = 23,
		DressFront_jnt      = 24
	};

	/**
	 * BoneSkeletalMesh SK_Tilt_Arm.SK_Tilt_Arm
	 */
	enum class EBone_SK_Tilt_Arm : uint8_t
	{
		Root                = 0,
		upperarm_l          = 1,
		lowerarm_l          = 2,
		hand_l              = 3,
		index_01_l          = 4,
		index_02_l          = 5,
		index_03_l          = 6,
		middle_01_l         = 7,
		middle_02_l         = 8,
		middle_03_l         = 9,
		ring_01_l           = 10,
		ring_02_l           = 11,
		ring_03_l           = 12,
		pinky_01_l          = 13,
		pinky_02_l          = 14,
		pinky_03_l          = 15,
		thumb_01_l          = 16,
		thumb_02_l          = 17,
		thumb_03_l          = 18,
		prop_l              = 19,
		lowerarm_twist_01_l = 20,
		puppet_main         = 21,
		Head                = 22,
		ear_01_l            = 23,
		ear_02_l            = 24,
		ear_03_l            = 25,
		ear_04_l            = 26,
		upperwhisker_01_l   = 27,
		upperwhisker_02_l   = 28,
		upperwhisker_03_l   = 29,
		lowerwhisker_01_l   = 30,
		lowerwhisker_02_l   = 31,
		lowerwhisker_03_l   = 32,
		lowerwhisker_04_l   = 33,
		ear_01_r            = 34,
		ear_02_r            = 35,
		ear_03_r            = 36,
		ear_04_r            = 37,
		upperwhisker_01_r   = 38,
		upperwhisker_02_r   = 39,
		upperwhisker_03_r   = 40,
		lowerwhisker_01_r   = 41,
		lowerwhisker_02_r   = 42,
		lowerwhisker_03_r   = 43,
		bow                 = 44,
		puppetshoulder_l    = 45,
		puppetwrist_l       = 46,
		puppetskirt         = 47,
		puppetshoulder_r    = 48,
		puppetwrist_r       = 49
	};

	/**
	 * BoneSkeletalMesh SK_FTChica_CupcakeOnly.SK_FTChica_CupcakeOnly
	 */
	enum class EBone_SK_FTChica_CupcakeOnly : uint8_t
	{
		Root             = 0,
		DynamicLight_jnt = 1,
		Jumpscare_jnt    = 2,
		pelvis           = 3,
		thigh_l          = 4,
		calf_l           = 5,
		foot_l           = 6,
		ball_l           = 7,
		ballEND_l        = 8,
		spine_01         = 9,
		neck_01          = 10,
		neck_02          = 11,
		jawOuter         = 12,
		eye_l            = 13,
		upperlid_l       = 14,
		lowerlid_l       = 15,
		brow_l           = 16,
		eye_r            = 17,
		upperlid_r       = 18,
		lowerlid_r       = 19,
		brow_r           = 20,
		lowerFaceShell_l = 21,
		lowerFaceShell_r = 22,
		eyeALL_l         = 23,
		eyeALL_r         = 24,
		jawInner         = 25,
		upperFaceShell_l = 26,
		upperFaceShell_r = 27,
		jawOuter_r       = 28,
		upperarm_l       = 29,
		lowerarm_l       = 30,
		hand_l           = 31,
		ring_01_l        = 32,
		ring_02_l        = 33,
		ring_03_l        = 34,
		middle_01_l      = 35,
		middle_02_l      = 36,
		middle_03_l      = 37,
		index_01_l       = 38,
		index_02_l       = 39,
		index_03_l       = 40,
		thumb_01_l       = 41,
		thumb_02_l       = 42,
		thumb_03_l       = 43,
		prop_l           = 44,
		pinky_01_l       = 45,
		pinky_02_l       = 46,
		pinky_03_l       = 47,
		upperarm_r       = 48,
		lowerarm_r       = 49,
		hand_r           = 50,
		ring_01_r        = 51,
		ring_02_r        = 52,
		ring_03_r        = 53,
		middle_01_r      = 54,
		middle_02_r      = 55,
		middle_03_r      = 56,
		index_01_r       = 57,
		index_02_r       = 58,
		index_03_r       = 59,
		thumb_01_r       = 60,
		thumb_02_r       = 61,
		thumb_03_r       = 62,
		prop_r           = 63,
		pinky_01_r       = 64,
		pinky_02_r       = 65,
		pinky_03_r       = 66,
		thigh_r          = 67,
		calf_r           = 68,
		foot_r           = 69,
		ball_r           = 70,
		ballEND_r        = 71,
		CupCake_root     = 72,
		CupCake_plate    = 73,
		CupCake_body     = 74,
		CupCake_upper    = 75,
		CupCake_lower    = 76,
		cupcake_eye_l    = 77,
		cupcake_eye_r    = 78
	};

	/**
	 * BoneSkeletalMesh SK_Bidybab_Arm.SK_Bidybab_Arm
	 */
	enum class EBone_SK_Bidybab_Arm : uint8_t
	{
		Root             = 0,
		DynamicLight_jnt = 1,
		Jumpscare_jnt    = 2,
		pelvis           = 3,
		thigh_l          = 4,
		calf_l           = 5,
		foot_l           = 6,
		ball_l           = 7,
		ballEND_l        = 8,
		spine_01         = 9,
		neck_01          = 10,
		neck_02          = 11,
		eye_l            = 12,
		upperlid_l       = 13,
		lowerlid_l       = 14,
		jaw              = 15,
		eye_r            = 16,
		upperlid_r       = 17,
		lowerlid_r       = 18,
		lowerFaceShell_l = 19,
		lowerFaceShell_r = 20,
		eyeALL_l         = 21,
		eyeALL_r         = 22,
		upperFaceShell   = 23,
		upperarm_l       = 24,
		lowerarm_l       = 25,
		hand_l           = 26,
		prop_l           = 27,
		upperarm_r       = 28,
		lowerarm_r       = 29,
		hand_r           = 30,
		prop_r           = 31,
		thigh_r          = 32,
		calf_r           = 33,
		foot_r           = 34,
		ball_r           = 35,
		ballEND_r        = 36
	};

	/**
	 * BoneSkeletalMesh RIG_Right_PlayerHands_10k.RIG_Right_PlayerHands_10k
	 */
	enum class EBone_RIG_Right_PlayerHands_10k : uint8_t
	{
		C_World_jnt             = 0,
		MannequinHand_Right_jnt = 1,
		hand_r_jnt              = 2,
		index_01_r_jnt          = 3,
		index_02_r_jnt          = 4,
		index_03_r_jnt          = 5,
		middle_01_r_jnt         = 6,
		middle_02_r_jnt         = 7,
		middle_03_r_jnt         = 8,
		ring_01_r_jnt           = 9,
		ring_02_r_jnt           = 10,
		ring_03_r_jnt           = 11,
		pinky_01_r_jnt          = 12,
		pinky_02_r_jnt          = 13,
		pinky_03_r_jnt          = 14,
		thumb_01_r_jnt          = 15,
		thumb_02_r_jnt          = 16,
		thumb_03_r_jnt          = 17
	};

	/**
	 * BoneSkeletalMesh SK_ST_CS_Freddy_Rig.SK_ST_CS_Freddy_Rig
	 */
	enum class EBone_SK_ST_CS_Freddy_Rig : uint8_t
	{
		C_World_jnt                   = 0,
		Root_jnt                      = 1,
		Spine_jnt                     = 2,
		Spine1_jnt                    = 3,
		Tie_jnt                       = 4,
		Neck_jnt                      = 5,
		Head_jnt                      = 6,
		Jaw_jnt                       = 7,
		Jaw_Jiggle_jnt                = 8,
		L_EyeALL_jnt                  = 9,
		L_Eye_jnt                     = 10,
		L_UpperEyelid_jnt             = 11,
		L_LowerEyelid_jnt             = 12,
		R_EyeALL_jnt                  = 13,
		R_Eye_jnt                     = 14,
		R_UpperEyelid_jnt             = 15,
		R_LowerEyelid_jnt             = 16,
		Hat_jnt                       = 17,
		HeadTop_Jiggle_jnt            = 18,
		HeadMiddle_Jiggle_jnt         = 19,
		Snout_Jiggle_jnt              = 20,
		Snout_button_CON              = 21,
		L_Ear_jnt                     = 22,
		L_EarEND_jnt                  = 23,
		L_Earing_jnt                  = 24,
		L_EarEndOuter_jnt             = 25,
		R_Ear_jnt                     = 26,
		R_EarEND_jnt                  = 27,
		R_EarEndOuter_jnt             = 28,
		Jaw2_jnt                      = 29,
		L_Shoulder_jnt                = 30,
		L_Elbow_jnt                   = 31,
		L_Wrist_jnt                   = 32,
		L_Prop_jnt                    = 33,
		L_PinkyA_jnt                  = 34,
		L_PinkyB_jnt                  = 35,
		L_PinkyBShell_jnt             = 36,
		L_PinkyAShell_jnt             = 37,
		L_MiddleA_jnt                 = 38,
		L_MiddleB_jnt                 = 39,
		L_MiddleBShell_jnt            = 40,
		L_MiddleAShell_jnt            = 41,
		L_IndexA_jnt                  = 42,
		L_IndexB_jnt                  = 43,
		L_IndexBShell_jnt             = 44,
		L_IndexAShell_jnt             = 45,
		L_ThumbA_jnt                  = 46,
		L_ThumbB_jnt                  = 47,
		L_ThumbBShell_jnt             = 48,
		L_ThumbAShell_jnt             = 49,
		L_WristShell_jnt              = 50,
		L_Forearm_Shell_jnt           = 51,
		L_Forearm_Hinge_1_JNT         = 52,
		L_Forearm_HingeSocket_jnt     = 53,
		L_Forearm_Hinge_2_JNT         = 54,
		L_Shoulder_Jiggle_jnt         = 55,
		L_ShoulderPad_jnt             = 56,
		R_ShoulderPad_jnt             = 57,
		R_Shoulder_jnt                = 58,
		R_Elbow_jnt                   = 59,
		R_Wrist_jnt                   = 60,
		R_Prop_jnt                    = 61,
		R_PinkyA_jnt                  = 62,
		R_PinkyB_jnt                  = 63,
		R_PinkyBShell_jnt             = 64,
		R_PinkyAShell_jnt             = 65,
		R_MiddleA_jnt                 = 66,
		R_MiddleB_jnt                 = 67,
		R_MiddleBShell_jnt            = 68,
		R_MiddleAShell_jnt            = 69,
		R_IndexA_jnt                  = 70,
		R_IndexB_jnt                  = 71,
		R_IndexBShell_jnt             = 72,
		R_IndexAShell_jnt             = 73,
		R_ThumbA_jnt                  = 74,
		R_ThumbB_jnt                  = 75,
		R_ThumbBShell_jnt             = 76,
		R_ThumbAShell_jnt             = 77,
		R_WristShell_jnt              = 78,
		R_Forearm_Shell_jnt           = 79,
		R_Forearm_Hinge_1_JNT         = 80,
		R_Forearm_HingeSocket_jnt     = 81,
		R_Forearm_Hinge_2_JNT         = 82,
		R_Shoulder_Jiggle_jnt         = 83,
		Spine1_Jiggle_jnt             = 84,
		ChestPlateTop_jnt             = 85,
		ChestPlateTop2_jnt            = 86,
		ChestPlateTop3_jnt            = 87,
		ChestPlateTop4_jnt            = 88,
		Voicebox_jnt                  = 89,
		Spine_Jiggle_jnt              = 90,
		ChestPlateBottom_jnt          = 91,
		ChestPlateBottom2_jnt         = 92,
		ChestPlateBottom3_jnt         = 93,
		ChestPlateBottom4_jnt         = 94,
		L_UpperLeg_jnt                = 95,
		L_Knee_jnt                    = 96,
		L_Ankle_jnt                   = 97,
		L_Toe_jnt                     = 98,
		L_Knee_Jiggle_jnt             = 99,
		L_UpperLeg_Jiggle_jnt         = 100,
		R_UpperLeg_jnt                = 101,
		R_Knee_jnt                    = 102,
		R_Ankle_jnt                   = 103,
		R_Toe_jnt                     = 104,
		R_Knee_Jiggle_jnt             = 105,
		R_UpperLeg_Jiggle_jnt         = 106,
		Root_Jiggle_jnt               = 107,
		R_AnkleIK_tracking_jnt        = 108,
		L_AnkleIK_tracking_jnt        = 109,
		L_Knee_PV__tracking_jnt       = 110,
		R_Knee_PV__tracking_jnt       = 111,
		World_Prop_jnt                = 112,
		Jumpscare_jnt                 = 113,
		ChestGateA_jnt                = 114,
		ChestGateB_jnt                = 115,
		L_Forearm_BatteryPositive_jnt = 116,
		L_Forearm_BatteryNegative_jnt = 117,
		L_Forearm_BatteryCenter_jnt   = 118,
		R_Forearm_StarPlug_jnt        = 119
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
